version: "2"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=graylog
      - MONGODB_ADMIN_USER=graylog
      - MONGODB_ADMIN_PASS=secret
      - MONGODB_APPLICATION_USER=graylog
      - MONGODB_APPLICATION_PASS=secret
    command: mongod
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: "on-failure"
    volumes:
      - /data/graylog/mongo_data:/data/db
    networks:
      - graylog
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    volumes:
      - /data/graylog/es_data:/var/lib/elasticsearch/data:rw
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - graylog
  graylog:
    image: graylog/graylog:5.1.2
    volumes:
      - /data/graylog/graylog_journal:/var/lib/graylog/data/journal:rw
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_PASSWORD_SECRET=z8mLcpBKRN4dfJqD73i9eme1h0BEnxiK1zhIkjfhOKocRDGteCiO3qgWEpkD997fvL0P09s2z2AkIHudz6lPlIVZHrpTUKAn
      - GRAYLOG_ROOT_PASSWORD_SHA2=aaebeea70dbe69a0d72a3f8d1adf7b88b2bb284d880cb47f3e4ebfe0982984b3
      # - GRAYLOG_MONGODB_URI=mongodb://user:passs@mongodb:27017/graylog
    links:
      - mongodb:mongo
      - elasticsearch
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    depends_on:
      mongodb:
        condition: "service_started"
      elasticsearch:
        condition: "service_started"
    networks:
      - graylog
    ports:
      - 8080:9000
      - 9000:9000
      - 514:514
      - 514:514/udp
      - 12201:12201
      - 12201:12201/udp
networks:
  graylog:
    driver: bridge
